language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
script:
  - npm t
  - npm run build
  - npm run size
after_success:
  - npx codecov
deploy:
  - provider: script
    script: npx now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: npx now --token $NOW_TOKEN && npx now alias dev.analogic.al --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: development
  - provider: script
    script: npx now --token $NOW_TOKEN && npx now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
