language: node_js

node_js:
  - node

jobs:
  fast_finish: true
  include:
    - script:
        - npm run test
    - stage: staging
      if: type in (pull_request)
      script:
        - export NOW_ALIAS=$ALIAS_DEV
        - now-travis
    - stage: deploy
      if: branch = master
      script:
        - export NOW_ALIAS=$ALIAS_PROD
        - now-travis

