language: node_js

node_js:
  - "10"

cache:
  directories:
    - "node_modules"

install:
  - npm ci

script:
  - npm t
  - npm run build
  - npm run size

after_success:
  - npx codecov

deploy:
  - provider: script
    script: npm run release
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
