language: node_js
node_js:
  - "node"

env:
  - NODE_ENV=development

before_install:
  - npx codecov

install:
  - npm ci

script:
  - npm t
  - npm run build
  - npx codecov

notifications:
  email: false
