language: node_js

node_js:
  - node

cache: yarn

script:
  - npm run test

after_success:
  - yarn global add now
  - now -t $NOW_TOKEN
  - now alias $NOW_ALIAS -t $NOW_TOKEN
  - now rm $NOW_NAME -s -y -t $NOW_TOKEN

deploy:
  provider: script
  script:
    - now alias -t $NOW_TOKEN
  on:
    branch: master

