language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
script:
  - npm t
  - npm run build
  - npm run size
after_success:
  - npx codecov
deploy:
  - provider: script
    script: npm run deploy
    skip_cleanup: true
    on:
      master: false
      develop: false
      all_branches: true
  - provider: script
    script: npm run deploy:dev
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master
  - provider: script
    script: npm run deploy:prod
    skip_cleanup: true
    on:
      branch: master
notifications:
  email: false
