language: node_js
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
install:
  - npm ci
script:
  - npm t
  - npm run build
  - npx codecov
deploy:
  - provider: script
    script: npx now --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      master: false
  - provider: script
    script: npx now --token $NOW_TOKEN && now alias --token $NOW_TOKEN
    skip_cleanup: true
    on:
      master: true
notifications:
  email: false
