language: node_js

node_js:
  - node

cache: yarn

stages:
  - name: staging
    if: type = pull_request
  - name: deploy
    if: branch = master

jobs:
  include:

    - stage: staging
      script:
        - yarn global add now commit-status
        - commit-status pending stage "Deploying to Δ Now ..."
        - now -t $NOW_TOKEN > url
        - commit-status success stage "Deploy is ready!" $(<url)
        - now alias $NOW_STAGE_URL -t $NOW_TOKEN
        - now rm $NOW_APP -y -s -t $NOW_TOKEN
    
    - stage: production
      script:
        - yarn global add now commit-status
        - commit-status pending production "Deploying to Δ Now ..."
        - now -t $NOW_TOKEN > url
        - commit-status success production "Deploy is ready!" $(<url)
        - now alias -t $NOW_TOKEN