language: node_js
node_js:
  - node
cache: false
stages:
  - testing
  - name: staging
    if: type IN (push, pull_request)
  - name: producion
    if: branch = master
jobs:
  fast_finish: true
  include:
    - stage: testing
      script:
        - yarn add codecov commit-status
        - commit-status pending testing "Running tests ..."
        - npm run test:cover
        - codecov
        - commit-status success testing "Test passed!"
    - stage: staging
      script:
        - yarn global add now commit-status
        - commit-status pending staging "Deploying to Δ Now ..."
        - now -t $NOW_TOKEN
        - now alias $NOW_STAGE_URL -t $NOW_TOKEN
        - commit-status success staging "Deploy is ready!" https://$NOW_STAGE_URL
    - stage: production
      script:
        - yarn global add now commit-status
        - commit-status pending production "Deploying to Δ Now ..."
        - now -t $NOW_TOKEN
        - commit-status success production "Deploy is ready!"
        - now alias -t $NOW_TOKEN
notifications:
  email:
    on_success: never