language: node_js

node_js:
  - node

cache: yarn

# script:
#   - npm test:cover
#   - codecove

deploy:
  - provider: script
    script:
      - now alias -t $NOW_TOKEN
    branches:
      only:
        - master
  - provider: script
    script:
      - now alias $NOW_STAGE_URL -t $NOW_TOKEN
    branches:
      only:
        - /feature/