language: node_js

node_js:
  - node

cache: yarn

script:
  - npm run test

after_success:
  - yarn global add now commit-status
  - export NOW_ALIAS=$ALIAS_DEV
  - commit-status pending stage "Deploying to Î” Now ..."
  - now -t $NOW_TOKEN > url
  - commit-status success stage "Deploy is ready!" $(<url)
  - now rm $NOW_NAME -y -s -t $NOW_TOKEN
  if: type IS pull_request

deploy:
  provider: script
  script:
    - now alias -t $NOW_TOKEN
  on:
    branch: master


