language: node_js

node_js:
  - node

cache: false

script:
  - npm test

jobs:
  fast_finish: true
  include:
    - stage: staging
      if: type in (pull_request)
      script:
        - yarn global add now commit-status
        - commit-status pending staging "Deploying to Δ Now ..."
        - now -t $NOW_TOKEN > url
        - now alias $NOW_STAGE_URL -t $NOW_TOKEN
        - now rm $NOW_APP -y -s -t $NOW_TOKEN
        - commit-status success staging "Deploy is ready!" https://$NOW_STAGE_URL
    - stage: production
      if: branch in (master)
      script:
        - yarn global add now commit-status
        - commit-status pending production "Deploying to Δ Now ..."
        - now -t $NOW_TOKEN
        - commit-status success production "Deploy is ready!"
        - now alias -t $NOW_TOKEN

notifications:
  email:
    on_success: never